CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  login VARCHAR(80) NOT NULL UNIQUE,
  senha_hash VARCHAR(255) NOT NULL,
  perfil VARCHAR(20) NOT NULL DEFAULT 'ATENDENTE'
    CHECK (perfil IN ('ATENDENTE', 'GESTOR')),
  ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS guiches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero INTEGER NOT NULL UNIQUE,
  ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS senhas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero VARCHAR(20) NOT NULL UNIQUE,
  tipo VARCHAR(2) NOT NULL CHECK (tipo IN ('SP', 'SE', 'SG')),
  sequencia INTEGER NOT NULL,
  estado VARCHAR(24) NOT NULL DEFAULT 'EMITIDA'
    CHECK (estado IN (
      'EMITIDA', 'AGUARDANDO', 'CHAMADA', 'CHAMADA_NOVAMENTE',
      'EM_ATENDIMENTO', 'ATENDIDA', 'NAO_COMPARECEU'
    )),
  emitida_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  primeira_chamada_em TIMESTAMPTZ,
  segunda_chamada_em TIMESTAMPTZ,
  inicio_atendimento_em TIMESTAMPTZ,
  fim_atendimento_em TIMESTAMPTZ,
  usuario_id INTEGER REFERENCES usuarios(id),
  guiche_id INTEGER REFERENCES guiches(id)
);

CREATE INDEX IF NOT EXISTS idx_fila ON senhas (estado, tipo, emitida_em, id);
CREATE INDEX IF NOT EXISTS idx_emitida ON senhas (emitida_em);

CREATE TABLE IF NOT EXISTS sequencias_senhas (
  dia DATE NOT NULL,
  tipo VARCHAR(2) NOT NULL CHECK (tipo IN ('SP', 'SE', 'SG')),
  sequencia INTEGER NOT NULL CHECK (sequencia > 0),
  PRIMARY KEY (dia, tipo)
);

CREATE TABLE IF NOT EXISTS fila_controle (
  id SMALLINT PRIMARY KEY CHECK (id = 1),
  ultimo_tipo VARCHAR(2) CHECK (ultimo_tipo IS NULL OR ultimo_tipo IN ('SP', 'SE', 'SG'))
);

CREATE TABLE IF NOT EXISTS auditoria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  senha_id BIGINT NOT NULL REFERENCES senhas(id),
  usuario_id INTEGER REFERENCES usuarios(id),
  guiche_id INTEGER REFERENCES guiches(id),
  evento VARCHAR(50) NOT NULL,
  realizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  detalhes VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_auditoria_realizado_em ON auditoria (realizado_em);

INSERT INTO guiches (numero) VALUES (1), (2), (3), (4)
ON CONFLICT (numero) DO NOTHING;

INSERT INTO fila_controle (id, ultimo_tipo) VALUES (1, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO usuarios (nome, login, senha_hash, perfil)
VALUES (
  'Atendente Demo',
  'atendente',
  '$2b$10$LaKvGlSZiLLHqYQsGTO5euf74em0iUh8dURce4CyEp22Askpocnf.',
  'GESTOR'
)
ON CONFLICT (login) DO NOTHING;
